### ISSUE TITLE
Minimum iOS Requirement

### ISSUE THREAD

**Issue by varatep** [zhxnlai/ZLBalancedFlowLayout#3]
Documentation states iOS 6.
Podspec and Cocoapods states iOS 8.

**Comment by zhxnlai** [comment]
Thanks for asking! ZLBalanceFlowLayout is a subclass of [UICollectionViewFlowLayout](https://developer.apple.com/library/prerelease/ios/documentation/UIKit/Reference/UICollectionViewFlowLayout_class/index.html#//apple_ref/swift/cl/UICollectionViewFlowLayout) which is available since iOS 6. But it is written in Swift and cocoapod's support for Swift project requires at least iOS 8. So if you want to use ZLBalanceFlowLayout in deployment target before iOS 8, I would suggest you to download the [source](https://github.com/zhxnlai/ZLBalancedFlowLayout/blob/master/ZLBalancedFlowLayout/ZLBalancedFlowLayout.swift) and add it to your project manually.
